x <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
y <- subset(x, Date == "1/2/2007" | Date == "2/2/2007")
png("plot1.png", width = 480, height = 480)
hist(y$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()