x <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
y <- subset(x, Date == "1/2/2007" | Date == "2/2/2007")
y$Date <- strptime(paste(y$Date,y$Time), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
plot(y$Date, y$Global_active_power, xlab = " ", ylab = "Global Active Power (kilowatts)", pch=46, type = "l")
plot(y$Date, y$Voltage, xlab = "datetime", ylab = "Voltage", type = "l")
plot(y$Date, y$Sub_metering_1, xlab = " ", ylab = "Energy sub metering", type = "l")
lines(y$Date, y$Sub_metering_2, type = "l", col = "red")
lines(y$Date, y$Sub_metering_3, type = "l", col = "blue")
labels <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
legend("topright", labels, lty=1, col = c("black", "red", "blue"), bty = "n")
plot(y$Date, y$Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "l")
dev.off()